openapi: 3.0.3
info:
  title: Library API
  version: 1.3.0
  description: STD22055
servers:
  - url: https://library.com
paths:
  /books:
    get:
      tags:
        - "Books"
      summary: Get all books
      description: The returned books are ordered by updated datetime.
      operationId: getBooks
      parameters:
        - in: query
          name: bookName
          description: Filter return books by given name
          required: false
          schema:
            type: string
        #TODO3: add parameter to filter books by intervals of dates of the releaseDate
        - in: query
          name: releaseDateRange
          description: Filter books by release date range
          required: false
          schema:
            type: string
            format: date
        - $ref: '#/components/parameters/queryPage'
        - $ref: '#/components/parameters/queryPageSize'
      responses:
        200:
          $ref: '#/components/responses/BookList_200'
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500:
          $ref: '#/components/responses/500'

    put:
      tags:
        - "Books"
      summary: Create or update a list of books
      operationId: crupdateBooks
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/CrupdateBooks"
      responses:
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500:
          $ref: '#/components/responses/500'
  /books/{bookId}:
    delete:
      tags:
        - "Books"
      summary: Remove books
      operationId: deleteBooks
      parameters:
        - in: query
          name: Remove books
          description: Delete book by id
          required: true
          schema:
            type: string
      responses:
        200:
          $ref: '#/components/schemas/BookListBody'
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500:
          $ref: '#/components/responses/500'

  /authors:
    get:
      tags:
        - "Authors"
      summary: Get all authors
      description: Retrieve a list of authors, filterable by name
      operationId: getAuthors
      parameters:
        - in: query
          name: authorName
          description: Filter authors by name
          required: false
          schema:
            type: string
        - $ref: '#/components/parameters/pathPageSize'
        - $ref: '#/components/parameters/pathPage'
      responses:
        200:
          description: The list of authors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/BookListBody"
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500:
          $ref: '#/components/responses/500'
    #TODO2: complete GET (can be filtered by name) - PUT - DELETE
    put:
      tags:
        - "Authors"
      summary: Create or update authors
      operationId: crupdateAuthors
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Author"
      responses:

        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500:
          $ref: '#/components/responses/500'
  /authors/{authorId}:
    delete:
      tags:
        - "Authors"
      summary: Delete authors
      operationId: deleteAuthors
      parameters:
        - in: path
          name: id
          description: Remove author by given id
          required: true
          schema:
            type: string
      responses:

        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500:
          $ref: '#/components/responses/500'
  /books/authors:
    put:
      tags:
        - Books
      summary: Modify authors for a books by Id
      operationId: updateBooks
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  bookId:
                    type: string
                  authorId:
                    type: string
                required:
                  - "bookId"
                  - "authorId"
      responses:

        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500:
          $ref: '#/components/responses/500'
  /import/book:
    post:
      summary: Import book from JSON/excel file
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ImportDataBook"
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500:
          $ref: '#/components/responses/500'
  /import/author:
    post:
      summary: Import author from Excel or JSON file
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ImportDataAuthor"
      responses:
        '200':
          description:  OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  
components:
  schemas:
    Visitors:
      type: object
      properties:
        visitorId:
          type: integer
        visitorName:
          type: string
        reference:
          type: string



    CrupdateTopic:
      type: object
      properties:
        topicName:
          type: string
    Topic:
      type: object
      allOf:
        - properties:
            id:
              type: string
        - $ref: "#/components/schemas/CrupdateTopic"

    CrupdateBooks:
      type: object
      properties:
        bookName:
          type: string
        pageNumbers:
          type: integer
        releaseDate:
          type: string
          format: date

    CrupdateAuthors:
      type: object
      properties:
        authorName:
          type: string
        sex:
          $ref: "#/components/schemas/Sex"

    Sex:
      type: string
      enum:
        - M
        - F
    Author:
      type: object
      allOf:
        - properties:
            id:
              type: string
        - allOf:
            - $ref: "#/components/schemas/CrupdateAuthors"

    Book:
      type: object
      allOf:
        - properties:
            id:
              type: string
            author:
              allOf:
                - $ref: "#/components/schemas/Author"
            Topic:
              allOf:
                - $ref: "#/components/schemas/Topic"
        - $ref: "#/components/schemas/CrupdateBooks"

    UpdateBookAuthor:
      type: object
      properties:
        bookId:
          type: string
        authorId:
          type: string
      required:
        - "bookId"
        - "authorId"

    ImportDataBook:
      type: object
      oneOf:
        - $ref: "#/components/schemas/ImportBookJSON"
        - $ref: "#/components/schemas/ImportBookExcel"
    ImportBookJSON:
      type: object
      properties:
        books:
          type: array
          items:
            $ref: "#/components/schemas/Book"
    ImportBookExcel:
      type: object
      properties:
        excelFile:
          type: string
          example: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    ImportDataAuthor:
      type: object
      oneOf:
        - $ref: "#/components/schemas/ImportAuthorJSON"
        - $ref: "#/components/schemas/ImportAuthorExcel"
    ImportAuthorJSON:
      type: object
      properties:
        authors:
          type: array
          items:
            $ref: "#/components/schemas/Author"
    ImportAuthorExcel:
      type: object
      properties:
        excelFile:
          type: string
          format: binary
          example: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    ResponseBodyTemplate:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/ResponsesStatus'
        body:
          type: object
    ResponsesStatus:
      type: object
      properties:
        code:
          type: integer
          example: 200
        message:
          type: string
    BadRequest:
      allOf:
        - $ref: '#/components/schemas/ResponseBodyTemplate'
      example:
        status:
          code: 400
          message: BAD REQUEST
        body: {}

    ForbiddenOperation:
      allOf:
        - $ref: '#/components/schemas/ResponseBodyTemplate'
      example:
        status:
          code: 403
          message: FORBIDDEN
        body: {}

    InternalServerError:
      allOf:
        - $ref: '#/components/schemas/ResponseBodyTemplate'
      example:
        status:
          code: 500
          message: Internal Server Error
        body: {}
    BookListBody:
      description:  List of books
      allOf:
        - $ref: '#/components/schemas/ResponseBodyTemplate'
        - properties:
            body:
              type: array
              items:
                $ref: '#/components/schemas/Book'
  parameters:
    queryPage:
      in: query
      name: QueryPage
      schema:
        type: integer
        default: 1
    queryPageSize:
      in: query
      name: QueryPageSize
      schema:
        type: integer
        default: 50
    pathPage:
      in: path
      name: PathPage
      schema:
        type: integer
        default: 1
    pathPageSize:
      in: path
      name: PathPageSize
      schema:
        type: integer
        default: 50
  responses:
    BookList_200:
      description: List of the books
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/BookListBody"
    400:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/BadRequest"
    403:
      description: Forbidden operation
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ForbiddenOperation"

    500:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/InternalServerError"









